### ISSUE TITLE
게임 해상도 높이기(업 스케일링)

### ISSUE THREAD

**Issue by GN-cat** [inha-codeduck/indeok-and-annyong-game#30]
게임 해상도 544X400 -> 1024X768 로 업 스케일링

청 크 사이즈 32 

1. Display size 변경
2. Board size 변경
3. 맵 offset 변경
4. 업 스케일링에 따른 door 와 gate 위치 변경
5. 캐릭터 조정(점프, 속도)

**Comment by leejongyoung** [comment]
Resolution: 680x480
